export const APPLICATION_CHANGE_TAB = "APPLICATION_CHANGE_TAB"
export const APPLICATION_SHOW_SPINNER = "APPLICATION_SHOW_SPINNER"
export const APPLICATION_FETCH_STORES_FOR_SELECT = "APPLICATION_FETCH_STORES_FOR_SELECT"
export const APPLICATION_FETCH_BOOKS_FOR_SELECT = "APPLICATION_FETCH_BOOKS_FOR_SELECT"
export const APPLICATION_USER_LOGGED = "APPLICATION_USER_LOGGED"
export const APPLICATION_SHOW_TOAST = "APPLICATION_SHOW_TOAST"
export const APPLICATION_SET_USER_DETAILS = "APPLICATION_SET_USER_DETAILS"
export const APPLICATION_SET_USER_ACCOUNT_BALANCE = "APPLICATION_SET_USER_ACCOUNT_BALANCE"

export const ADD_BOOK_BEGIN = "ADD_BOOK";
export const ADD_BOOK_ERROR = "ADD_BOOK_ERROR";
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";
export const ADD_BOOK_VALIDATION_ERRORS = "ADD_BOOK_VALIDATION_ERRORS"
export const ADD_BOOK_FIELD_CHANGE = "ADD_BOOK_FIELD_CHANGE"
export const ADD_BOOK_CLEAR = "ADD_BOOK_CLEAR"

export const ADD_STORE_BEGIN = "ADD_STORE_BEGIN"
export const ADD_STORE_ERROR = "ADD_STORE_ERROR"
export const ADD_STORE_SUCCESS = "ADD_STORE_SUCCESS"
export const ADD_STORE_VALIDATION_ERRORS = "ADD_STORE_VALIDATION_ERRORS"
export const ADD_STORE_FIELD_CHANGE = "ADD_STORE_FIELD_CHANGE"
export const ADD_STORE_MODAL = "ADD_STORE_MODAL"

export const BOOK_DETAILS_FETCH_STORES_BEGIN = "BOOK_DETAILS_FETCH_STORES_BEGIN"
export const BOOK_DETAILS_FETCH_STORES_ERROR = "BOOK_DETAILS_FETCH_STORES_ERROR"
export const BOOK_DETAILS_FETCH_STORES_SUCCESS = "BOOK_DETAILS_FETCH_STORES_SUCCESS"
export const BOOK_DETAILS_PAGE_NUMBER = "BOOK_DETAILS_PAGE_NUMBER"
export const BOOK_DETAILS_QUANTITY_CHANGE = "BOOK_DETAILS_QUANTITY_CHANGE"

export const BOOKS_FETCH_BEGIN = "BOOKS_FETCH_BEGIN"
export const BOOKS_FETCH_ERROR = "BOOKS_FETCH_ERROR"
export const BOOKS_FETCH_SUCCESS = "BOOKS_FETCH_SUCCESS"
export const BOOKS_PARAMS_CHANGE = "BOOKS_PARAMS_CHANGE"
export const BOOKS_PARAMS_CLEAR = "BOOKS_PARAMS_CLEAR"
export const BOOKS_CHANGE_PAGE = "BOOKS_CHANGE_PAGE"
export const BOOKS_STORE_CHANGE = "BOOKS_STORE_CHANGE"
export const BOOKS_MODAL = "BOOKS_MODAL"
export const BOOK_DETAILS_ID_CHANGE = "BOOK_DETAILS_ID_CHANGE"

export const CART_ADD = "CART_ADD";
export const CART_REMOVE = "CART_REMOVE"
export const CART_CLEAR_ERROR_MESSAGES = "CART_CLEAR_ERROR_MESSAGES"
export const CART_FIELD_CHANGE = "CART_FIELD_CHANGE";
export const CART_COMPLETE_PAYMENT_BEGIN = "CART_COMPLETE_PAYMENT_BEGIN"
export const CART_COMPLETE_PAYMENT_ERROR = "CART_COMPLETE_PAYMENT_ERROR"
export const CART_COMPLETE_PAYMENT_SUCCESS = "CART_COMPLETE_PAYMENT_SUCCESS"

export const LOGIN_BEGIN = "LOGIN_BEGIN";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FIELD_CHANGE = "LOGIN_FIELD_CHANGE";
export const LOGIN_CLEAR = "LOGIN_PAGE_CLEAR"

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_FIELD_CHANGE = "REGISTER_FIELD_CHANGE";
export const REGISTER_CLEAR = "REGISTER_PAGE_CLEAR"

export const STORES_FETCH_BEGIN = "STORES_FETCH_BEGIN"
export const STORES_FETCH_ERROR = "STORES_FETCH_ERROR"
export const STORES_FETCH_SUCCESS = "STORES_FETCH_SUCCESS"
export const STORES_PARAMS_CHANGE = "STORES_PARAMS_CHANGE"

export const STORE_BOOK_MODAL = "STORE_BOOK_MODAL"
export const STORE_BOOK_VALIDATION_ERRORS = "STORE_BOOK_VALIDATION_ERRORS"
export const STORE_BOOK_CLEAR = "STORE_BOOK_CLEAR"
export const STORE_BOOK_FIELD_CHANGE = "STORE_BOOK_FIELD_CHANGE"
export const STORE_BOOK_ADD_TO_LIST = "STORE_BOOK_ADD_TO_LIST"
export const STORE_BOOK_REMOVE_FROM_LIST = "STORE_BOOK_REMOVE_FROM_LIST"
export const STORE_BOOK_ADD_BOOKS_BEGIN = "STORE_BOOK_ADD_BOOKS_BEGIN"
export const STORE_BOOK_ADD_BOOKS_ERROR = "STORE_BOOK_ADD_BOOKS_ERROR"
export const STORE_BOOK_ADD_BOOKS_SUCCESS = "STORE_BOOK_ADD_BOOKS_SUCCESS"

export const TRANSACTIONS_FETCH_BEGIN = "TRANSACTIONS_FETCH_BEGIN"
export const TRANSACTIONS_FETCH_ERROR = "TRANSACTIONS_FETCH_ERROR"
export const TRANSACTIONS_FETCH_SUCCESS = "TRANSACTIONS_FETCH_SUCCESS"
export const TRANSACTIONS_DETAILS_FETCH_BEGIN = "TRANSACTIONS_DETAILS_FETCH_BEGIN"
export const TRANSACTIONS_DETAILS_FETCH_ERROR = "TRANSACTIONS_DETAILS_FETCH_ERROR"
export const TRANSACTIONS_DETAILS_FETCH_SUCCESS = "TRANSACTIONS_DETAILS_FETCH_SUCCESS"
export const TRANSACTIONS_SELECT_CHANGE = "TRANSACTIONS_SELECT_CHANGE"

